### PR TITLE
Add Big Sur Beta 2 developer download url

### PR DESCRIPTION
**Pull request by ZISQO**
it's working fine to download BS bt2

### CODE REVIEW

**Comment by gregneagle** [comment]
No changes to the code are needed to download the beta when running the tool on Catalina — just use the —seed option or —catalog option

**Comment by gregneagle** [comment]
No changes to the code are needed to download the beta when running the tool on Catalina — just use the —seed option or —catalog option

**Comment by ZISQO** [comment]
> No changes to the code are needed to download the beta when running the tool on Catalina — just use the —seed option or —catalog option

it just because of somebody can't update via System Preferences even if running developer beautility.pkg
so this is will be able to download enforcement.

**Comment by gregneagle** [comment]
If you are running it under Big Sur, you can use the --catalog option.

You'll notice the existing catalog URLs are the default URLs for the corresponding OS:

```python
DEFAULT_SUCATALOGS = {
    '17': 'https://swscan.apple.com/content/catalogs/others/'
          'index-10.13-10.12-10.11-10.10-10.9'
          '-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog',
    '18': 'https://swscan.apple.com/content/catalogs/others/'
          'index-10.14-10.13-10.12-10.11-10.10-10.9'
          '-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog',
    '19': 'https://swscan.apple.com/content/catalogs/others/'
          'index-10.15-10.14-10.13-10.12-10.11-10.10-10.9'
          '-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog',
}
```
I don't really want to put a temporary catalog in there and fix it later. I suspect the catalogURL will change along with the renumbering of Big Sur from 10.16 to 11.0.

Again, you can use the tool now with no code changes. I prefer to leave it this way for now.

**Pull request closed without merging**
